<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="pandoc" />

        <meta name="author" content="Tobias Lanzl" />
    
    
    <title>Stroke prediction with logistic regression</title>

        <script src="site_libs/header-attrs-2.17/header-attrs.js"></script>
        <script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="site_libs/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <script src="site_libs/bootstrap-3.3.7/js/bootstrap.min.js"></script>
        <script src="site_libs/navigation-1.1/tabsets.js"></script>
        <script src="site_libs/navigation-1.1/codefolding.js"></script>
        <link href="site_libs/readthedown-0.1/readthedown.css" rel="stylesheet" />
        <link href="site_libs/readthedown-0.1/readthedown_fonts_embed.css" rel="stylesheet" />
        <script src="site_libs/readthedown-0.1/readthedown.js"></script>
        <link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
        <link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
    
    
        <style type="text/css">code{white-space: pre;}</style>
    <style type="text/css">
      pre > code.sourceCode { white-space: pre; position: relative; }
      pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
      pre > code.sourceCode > span:empty { height: 1.2em; }
      .sourceCode { overflow: visible; }
      code.sourceCode > span { color: inherit; text-decoration: inherit; }
      div.sourceCode { margin: 1em 0; }
      pre.sourceCode { margin: 0; }
      @media screen {
      div.sourceCode { overflow: auto; }
      }
      @media print {
      pre > code.sourceCode { white-space: pre-wrap; }
      pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
      }
      pre.numberSource code
        { counter-reset: source-line 0; }
      pre.numberSource code > span
        { position: relative; left: -4em; counter-increment: source-line; }
      pre.numberSource code > span > a:first-child::before
        { content: counter(source-line);
          position: relative; left: -1em; text-align: right; vertical-align: baseline;
          border: none; display: inline-block;
          -webkit-touch-callout: none; -webkit-user-select: none;
          -khtml-user-select: none; -moz-user-select: none;
          -ms-user-select: none; user-select: none;
          padding: 0 4px; width: 4em;
          background-color: #ffffff;
          color: #a0a0a0;
        }
      pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
      div.sourceCode
        { color: #1f1c1b; background-color: #ffffff; }
      @media screen {
      pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
      }
      code span { color: #1f1c1b; } /* Normal */
      code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
      code span.an { color: #ca60ca; } /* Annotation */
      code span.at { color: #0057ae; } /* Attribute */
      code span.bn { color: #b08000; } /* BaseN */
      code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
      code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
      code span.ch { color: #924c9d; } /* Char */
      code span.cn { color: #aa5500; } /* Constant */
      code span.co { color: #898887; } /* Comment */
      code span.cv { color: #0095ff; } /* CommentVar */
      code span.do { color: #607880; } /* Documentation */
      code span.dt { color: #0057ae; } /* DataType */
      code span.dv { color: #b08000; } /* DecVal */
      code span.er { color: #bf0303; text-decoration: underline; } /* Error */
      code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
      code span.fl { color: #b08000; } /* Float */
      code span.fu { color: #644a9b; } /* Function */
      code span.im { color: #ff5500; } /* Import */
      code span.in { color: #b08000; } /* Information */
      code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
      code span.op { color: #1f1c1b; } /* Operator */
      code span.ot { color: #006e28; } /* Other */
      code span.pp { color: #006e28; } /* Preprocessor */
      code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
      code span.sc { color: #3daee9; } /* SpecialChar */
      code span.ss { color: #ff5500; } /* SpecialString */
      code span.st { color: #bf0303; } /* String */
      code span.va { color: #0057ae; } /* Variable */
      code span.vs { color: #bf0303; } /* VerbatimString */
      code span.wa { color: #bf0303; } /* Warning */
    </style>
    
    
    <!-- tabsets -->
    <script>
      $(document).ready(function () {
	  window.buildTabsets("toc");
      });
      $(document).ready(function () {
	  $('.tabset-dropdown > .nav-tabs > li').click(function () {
	      $(this).parent().toggleClass('nav-tabs-open')
	  });
      });
    </script>

    <!-- code folding -->
        <script>
      $(document).ready(function () {
	  	  	  window.initializeCodeFolding("show" === "show");
	        });
    </script>
    
    <!-- code download -->
    
    <!-- tabsets dropdown -->

    <style type="text/css">
      .tabset-dropdown > .nav-tabs {
	  display: inline-table;
	  max-height: 500px;
	  min-height: 44px;
	  overflow-y: auto;
	  background: white;
	  border: 1px solid #ddd;
	  border-radius: 4px;
      }
      
      .tabset-dropdown > .nav-tabs > li.active:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
	  content: "&#xe258;";
	  border: none;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs > li.active {
	  display: block;
      }

      .tabset-dropdown > .nav-tabs > li.active a {
  	  padding: 0 15px !important;
      }

      .tabset-dropdown > .nav-tabs > li > a,
      .tabset-dropdown > .nav-tabs > li > a:focus,
      .tabset-dropdown > .nav-tabs > li > a:hover {
	  border: none;
	  display: inline-block;
	  border-radius: 4px;
	  background-color: transparent;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li {
	  display: block;
	  float: none;
      }
      
      .tabset-dropdown > .nav-tabs > li {
	  display: none;
	  margin-left: 0 !important;
      }
    </style>
    
</head>

<body class="preload">

   	
         <!-- readthedown start -->   
   <div id="content" data-toggle="wy-nav-shift">
     <nav id="nav-top" role="navigation" aria-label="top navigation">
       <a role="button" href="#" data-toggle="wy-nav-top"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
     </nav>
         
      <div class="btn-group pull-right">
     <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
     <ul class="dropdown-menu" style="min-width: 50px;">
	    	    <li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
	    <li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
	    	    	         </ul>
   </div>
   
      
      <div class="navbar navbar-default  navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Tobias Lanzl</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li>
        <a href="index.html">Home</a>
      </li>
      <li>
        <a href="stroke_prediction.html">Stroke prediction</a>
      </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
        <a href="mailto:t.lanzl@gmx.net">
          <span class="fa fa-envelope fa-lg"></span>
           
        </a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/tobiaslanzl93/">
          <span class="fa fa-linkedin fa-lg"></span>
           
        </a>
      </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container -->
      </div><!--/.navbar -->
        
      <h1 class="title">Stroke prediction with logistic regression</h1>
      
         <!-- readthedown authors -->
   <div id="sidebar">
    <h2><a href="#content">Stroke prediction with logistic
regression</a></h2>
    <div id="toc">
      <ul>
      <li><a href="#introduction"
      id="toc-introduction">Introduction</a></li>
      <li><a href="#preparation" id="toc-preparation">Preparation</a>
      <ul>
      <li><a href="#gender" id="toc-gender">Gender</a></li>
      <li><a href="#age" id="toc-age">Age</a></li>
      <li><a href="#hypertension"
      id="toc-hypertension">Hypertension</a></li>
      <li><a href="#heart-disease" id="toc-heart-disease">Heart
      disease</a></li>
      <li><a href="#marriage-status" id="toc-marriage-status">Marriage
      status</a></li>
      <li><a href="#work-type" id="toc-work-type">Work type</a></li>
      <li><a href="#residence-type" id="toc-residence-type">Residence
      type</a></li>
      <li><a href="#glucose-level" id="toc-glucose-level">Glucose
      level</a></li>
      <li><a href="#bmi" id="toc-bmi">BMI</a></li>
      <li><a href="#smoking-status" id="toc-smoking-status">Smoking
      status</a></li>
      </ul></li>
      <li><a href="#prediction" id="toc-prediction">Prediction</a>
      <ul>
      <li><a href="#standard-model" id="toc-standard-model">Standard
      model</a></li>
      <li><a href="#weights-and-smote"
      id="toc-weights-and-smote">Weights and SMOTE</a></li>
      <li><a href="#regularization"
      id="toc-regularization">Regularization</a></li>
      </ul></li>
      </ul>
    </div>
    <div id="postamble" data-toggle="wy-nav-shift" class="status">
                  <p class="author"><span class="glyphicon glyphicon-user"></span> Tobias
Lanzl</p>
                        <p class="date"><span class="glyphicon glyphicon-calendar"></span> 23.11.2022</p>
          </div>
   </div>
     

   
      
   
<!-- Don't indent these lines or it will mess pre blocks indentation --> 
<div id="main">
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Welcome to my data science project, where we harness the power of logistic regression and the programming language R to develop a predictive model for stroke. Our aim is to leverage valuable data, including gender, age, BMI, and history of heart diseases, to identify individuals at a higher risk of experiencing a stroke.

Stroke is a critical medical condition that requires timely intervention to minimize its potentially severe consequences. By employing logistic regression, a popular statistical technique for binary classification, we can analyze the relationships between various risk factors and stroke occurrence. This enables us to build a robust model that accurately predicts the likelihood of stroke for individuals based on their specific attributes.

With the versatility and efficiency of R, a powerful programming language for statistical computing, we can handle data manipulation, exploratory analysis, and model building seamlessly. By incorporating essential features such as gender, age, BMI, and history of heart diseases, our project endeavors to contribute to early detection and proactive stroke prevention strategies.

Join us on this data-driven journey as we strive to enhance stroke risk assessment and ultimately improve the overall health outcomes for individuals at risk.
	
	
The data set I use for this can
be downloaded under [<a
href="https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset"
class="uri">https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset</a>].</p>
<p>Let’s first load the packages we will use:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmPerm)</span></code></pre></div>
</div>
<div id="preparation" class="section level1">
<h1>Preparation</h1>
<p>We load the data set and exam it.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;healthcare-dataset-stroke-data.csv&#39;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data)</span></code></pre></div>
<pre><code>## [1] 5110   12</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)</span></code></pre></div>
<pre><code>##  [1] &quot;id&quot;                &quot;gender&quot;            &quot;age&quot;              
##  [4] &quot;hypertension&quot;      &quot;heart_disease&quot;     &quot;ever_married&quot;     
##  [7] &quot;work_type&quot;         &quot;Residence_type&quot;    &quot;avg_glucose_level&quot;
## [10] &quot;bmi&quot;               &quot;smoking_status&quot;    &quot;stroke&quot;</code></pre>
<p>The data set contains 12 variables, with one column for the id, for
5110 observations. Our target variable is <strong>stroke</strong> coded
as 0 if the patient did not have a stroke and 1 if he/she did.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>stroke)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 4861  249</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(data<span class="sc">$</span>stroke), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.049</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>stroke <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>stroke)</span></code></pre></div>
<p>This data set is highly unbalanced with only 249 of the 5110 (4.9%)
having suffered from a stroke.</p>
<p>Since we have a manageable number of variables we will go through the
rest of the columns one by one and look at their distribution and their
relationship to the stroke column.</p>
<div id="gender" class="section level2">
<h2>Gender</h2>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>##  chr [1:5110] &quot;Male&quot; &quot;Female&quot; &quot;Male&quot; &quot;Female&quot; &quot;Female&quot; &quot;Male&quot; &quot;Male&quot; ...</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## Female   Male  Other 
##   2994   2115      1</code></pre>
<p>The first variable is the gender of the patient coded as ‘Male’,
‘Female’, and ‘Other’. Since there is only one observation containing
‘Other’ we will filter it out.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">!=</span> <span class="st">&#39;Other&#39;</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>gender)<span class="sc">/</span><span class="fu">nrow</span>(data), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
## Female   Male 
##   0.59   0.41</code></pre>
<p>The data set consists of 59% female and 41% male patients.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>gender_stroke <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gender, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>gender_stroke</span></code></pre></div>
<pre><code>##         stroke
## gender      0    1
##   Female 2853  141
##   Male   2007  108</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(gender_stroke)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  gender_stroke
## X-squared = 0.34, df = 1, p-value = 0.5598</code></pre>
<p>A confusion matrix of <strong>gender</strong> and
<strong>stroke</strong> and a chi-squared test show that there is no
association between both columns. We will therefore not use it in our
model.</p>
</div>
<div id="age" class="section level2">
<h2>Age</h2>
<p>The next column is the age of the patient in years.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>##  num [1:5109] 67 61 80 49 79 81 74 69 59 78 ...</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(age))<span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(stroke, age, <span class="at">fill =</span> stroke))<span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;cornflowerblue&#39;</span>, <span class="st">&#39;yellow&#39;</span>))<span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&#39;none&#39;</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(A, B)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-8-1.png" width="768" /></p>
<p>When we look at a histogram with a binwidth of 5 years we see that
the distribution is skewed towards a higher age with a second peak at
patients over 80.</p>
<p>We can also see a clear trend that patients who had a stroke were on
average older than patients who did not have a stroke.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_group =</span> <span class="fu">ceiling</span>(age<span class="sc">/</span><span class="dv">5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age_group) <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">risk =</span> <span class="fu">mean</span>(stroke <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_age =</span> <span class="fu">min</span>(age),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_age =</span> <span class="fu">max</span>(age),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_age =</span> <span class="fu">mean</span>(age)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> avg_age, <span class="at">y =</span> risk))<span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&#39;Risk of having a stroke&#39;</span>)<span class="sc">+</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Average age of the patient&#39;</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-9-1.png" width="768" /></p>
<p>When we group the patients into age groups with a size of five years
and calculate the risk of having a stroke as the percentage of patients
who suffered from one, we can see that the risk is staying close to 0
until an age of 30 and then increases exponentially.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lmp</span>(age <span class="sc">~</span> stroke, <span class="at">data =</span> data))</span></code></pre></div>
<pre><code>## [1] &quot;Settings:  unique SS &quot;
## Analysis of Variance Table
## 
## Response: age
##             Df R Sum Sq R Mean Sq Iter  Pr(Prob)    
## stroke       1   157097    157097 5000 &lt; 2.2e-16 ***
## Residuals 5107  2455000       481                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>hypertension)</span></code></pre></div>
<p>As a statistical test for the association between
<strong>age</strong> and <strong>stroke</strong> I chose an ANOVA with a
permutation test, since we have highly unbalanced sample sizes for
<strong>stroke</strong>. As expected from the visual examination of the
data the average age of patients who suffered from a stroke differs
significantly from the age of patients who did not.</p>
</div>
<div id="hypertension" class="section level2">
<h2>Hypertension</h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>hypertension)</span></code></pre></div>
<pre><code>##  Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 2 1 2 1 1 1 ...</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>hypertension)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 4611  498</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>hypertension)<span class="sc">/</span><span class="fu">nrow</span>(data), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 0.9 0.1</code></pre>
<p>The next column <strong>hypertension</strong> is coded 0 if the
patient does not have hypertension and 1 if he/she did. Only 10% of
patients have hypertension.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>hypertension_stroke <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hypertension, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>hypertension_stroke</span></code></pre></div>
<pre><code>##             stroke
## hypertension    0    1
##            0 4428  183
##            1  432   66</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(hypertension_stroke)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  hypertension_stroke
## X-squared = 81.573, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>When looking at the confusion matrix between
<strong>hypertension</strong> and <strong>stroke</strong>, we see that
13.3% of patients who have hypertension suffered from a stroke compared
to the 4.0% of patients without hypertension. The chi-squared test
between both variables is also highly significant.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(hypertension,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                 age))<span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-13-1.png" width="768" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_group =</span> <span class="fu">ceiling</span>(age<span class="sc">/</span><span class="dv">5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age_group) <span class="sc">%&gt;%</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">risk =</span> <span class="fu">mean</span>(hypertension <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_age =</span> <span class="fu">min</span>(age),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_age =</span> <span class="fu">max</span>(age),</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_age =</span> <span class="fu">mean</span>(age)) <span class="sc">%&gt;%</span> </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> avg_age, <span class="at">y =</span> risk))<span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&#39;Risk of having hypertension&#39;</span>)<span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Average age of the patient&#39;</span>)<span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-13-2.png" width="768" /></p>
<p>When we look at the association between <strong>hypertension</strong>
and <strong>age</strong>, we see that the average age of patients with
hypertension is higher than of patients without hypertension. But if we
look at the percentage of hypertension in age groups of five years we
see a flatter increase as with <strong>stroke</strong> but starting
earlier (at around 20 years).</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&lt;=</span> <span class="dv">50</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hypertension, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### Patients younger than 50&#39;</span>)</span></code></pre></div>
<div id="patients-younger-than-50" class="section level3">
<h3>Patients younger than 50</h3>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tmp<span class="sc">/</span><span class="fu">rowSums</span>(tmp), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##             stroke
## hypertension    0    1
##            0 0.99 0.01
##            1 0.97 0.03</code></pre>
<p>For patients younger than 50 3% of the patients with hypertension
suffered from a stroke compared to the 1% without hypertension.</p>
<p>Therefore, if we include <strong>hypertension</strong> into our model
it might be able to differentiate better between younger patients (below
50) who had a stroke and who did not.</p>
</div>
</div>
<div id="heart-disease" class="section level2">
<h2>Heart disease</h2>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>heart_disease)</span></code></pre></div>
<pre><code>##  num [1:5109] 1 0 1 0 0 0 1 0 0 0 ...</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>heart_disease <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>heart_disease)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>heart_disease)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 4833  276</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>hypertension)<span class="sc">/</span><span class="fu">nrow</span>(data), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 0.9 0.1</code></pre>
<p>The next column <strong>heart_disease</strong> is coded as 0 if the
patient does not have any heart disease and 1 if he/she does.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>heart_disease_stroke <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(heart_disease, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>heart_disease_stroke</span></code></pre></div>
<pre><code>##              stroke
## heart_disease    0    1
##             0 4631  202
##             1  229   47</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(heart_disease_stroke)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  heart_disease_stroke
## X-squared = 90.229, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>The distribution of <strong>heart_disease</strong> is similar as in
<strong>stroke</strong>. The confusion matrix and the chi-squared test
show a strong association between <strong>heart_disease</strong> and
<strong>stroke</strong>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(heart_disease,</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                 age))<span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-17-1.png" width="768" /></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_group =</span> <span class="fu">ceiling</span>(age<span class="sc">/</span><span class="dv">5</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age_group) <span class="sc">%&gt;%</span> </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">risk =</span> <span class="fu">mean</span>(heart_disease <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_age =</span> <span class="fu">min</span>(age),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_age =</span> <span class="fu">max</span>(age),</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_age =</span> <span class="fu">mean</span>(age)) <span class="sc">%&gt;%</span> </span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> avg_age, <span class="at">y =</span> risk))<span class="sc">+</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&#39;Risk of having a heart disease&#39;</span>)<span class="sc">+</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Average age of the patient&#39;</span>)<span class="sc">+</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-17-2.png" width="768" /></p>
<p>When looking at the association between
<strong>heart_disease</strong> and <strong>age</strong> in total and in
age groups, we see both times a similar result as with
<strong>stroke</strong>.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&lt;</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(heart_disease, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### Patients younger than 50&#39;</span>)</span></code></pre></div>
<div id="patients-younger-than-50-1" class="section level3">
<h3>Patients younger than 50</h3>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tmp<span class="sc">/</span><span class="fu">rowSums</span>(tmp), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##              stroke
## heart_disease    0    1
##             0 0.99 0.01
##             1 1.00 0.00</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">50</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(heart_disease, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### Patients older than 50&#39;</span>)</span></code></pre></div>
</div>
<div id="patients-older-than-50" class="section level3">
<h3>Patients older than 50</h3>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tmp<span class="sc">/</span><span class="fu">rowSums</span>(tmp), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##              stroke
## heart_disease    0    1
##             0 0.90 0.10
##             1 0.82 0.18</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### All patients&#39;</span>)</span></code></pre></div>
</div>
<div id="all-patients" class="section level3">
<h3>All patients</h3>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(heart_disease_stroke<span class="sc">/</span><span class="fu">rowSums</span>(heart_disease_stroke), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##              stroke
## heart_disease    0    1
##             0 0.96 0.04
##             1 0.83 0.17</code></pre>
<p>The confusion matrix between <strong>heart_disease</strong> and
<strong>stroke</strong> for patients younger than 50 show that no
patient with a heart disease had a stroke. The percentage of patients
which suffered from both a stroke and have a heart disease is also the
same for all patients and patients older than 50.</p>
<p>Therefore, I think that the column <strong>heart_disease</strong>
will not bring any additional information for the prediction of a
stroke.</p>
</div>
</div>
<div id="marriage-status" class="section level2">
<h2>Marriage status</h2>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>ever_married)</span></code></pre></div>
<pre><code>##  chr [1:5109] &quot;Yes&quot; &quot;Yes&quot; &quot;Yes&quot; &quot;Yes&quot; &quot;Yes&quot; &quot;Yes&quot; &quot;Yes&quot; &quot;No&quot; &quot;Yes&quot; &quot;Yes&quot; ...</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>ever_married)<span class="sc">/</span><span class="fu">nrow</span>(data), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
##   No  Yes 
## 0.34 0.66</code></pre>
<p>The marriage status of the patients is contained in the column
<strong>ever_married</strong> coded as ‘Yes’ and ‘No’, with 33% of
patients having never been married.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>marriage_stroke <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ever_married, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>marriage_stroke</span></code></pre></div>
<pre><code>##             stroke
## ever_married    0    1
##          No  1727   29
##          Yes 3133  220</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(marriage_stroke)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  marriage_stroke
## X-squared = 58.868, df = 1, p-value = 1.686e-14</code></pre>
<p>Using the same approach as before we can see that people who are or
have been married had a higher chance of suffering from a stroke.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(stroke,</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>                 age,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> stroke))<span class="sc">+</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>ever_married)<span class="sc">+</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;cornflowerblue&#39;</span>, <span class="st">&#39;yellow&#39;</span>))<span class="sc">+</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&#39;Was the patient ever married?&#39;</span>)<span class="sc">+</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&#39;none&#39;</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-21-1.png" width="768" /></p>
<p>But when we also take the age of the patients into account we can see
that people who were never married were simply younger and that within
patients who are or have been married the ones who suffered from a
stroke are also on average older.</p>
<p>Therefore this column adds no additional information and will not be
included in the model.</p>
</div>
<div id="work-type" class="section level2">
<h2>Work type</h2>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>work_type)</span></code></pre></div>
<pre><code>##  chr [1:5109] &quot;Private&quot; &quot;Self-employed&quot; &quot;Private&quot; &quot;Private&quot; &quot;Self-employed&quot; ...</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>work_type)</span></code></pre></div>
<pre><code>## 
##      children      Govt_job  Never_worked       Private Self-employed 
##           687           657            22          2924           819</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>work_type)<span class="sc">/</span><span class="fu">nrow</span>(data), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
##      children      Govt_job  Never_worked       Private Self-employed 
##          0.13          0.13          0.00          0.57          0.16</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> work_type))<span class="sc">+</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()<span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-22-1.png" width="768" /></p>
<p>The column <strong>work_type</strong> contains information about the
employment of the patients. The data contains children, patients working
for the government (Govt_job), patients who never worked (Never_worked),
and patients employed by the private sector (Private) or by themselves
(Self-employed).</p>
<p>Most patients worked for the private sector (57%) and people who
never worked are barely represented (&lt; 1%). The other classes are
fairly balanced.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(stroke, age, <span class="at">fill =</span> stroke))<span class="sc">+</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>work_type)<span class="sc">+</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;cornflowerblue&#39;</span>, <span class="st">&#39;yellow&#39;</span>))<span class="sc">+</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&#39;none&#39;</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-23-1.png" width="768" /></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>work_type, data<span class="sc">$</span>stroke)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### Share of people with a stroke per work type&#39;</span>)</span></code></pre></div>
<div id="share-of-people-with-a-stroke-per-work-type"
class="section level3">
<h3>Share of people with a stroke per work type</h3>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tmp<span class="sc">/</span><span class="fu">rowSums</span>(tmp), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                
##                    0    1
##   children      1.00 0.00
##   Govt_job      0.95 0.05
##   Never_worked  1.00 0.00
##   Private       0.95 0.05
##   Self-employed 0.92 0.08</code></pre>
<p>When looking at the association between <strong>work_type</strong>
and <strong>stroke</strong> while also taking <strong>age</strong> into
account, we see that it is mainly age separating the patients who
suffered from a stroke from those who did not and not the work type.
Only for children the average age of patients who suffered from a stroke
and those who did not did not differ, but less than 1% of children
suffered from a stroke.</p>
<p>Therefore, I decided not to include <strong>work_type</strong> into
the model.</p>
</div>
</div>
<div id="residence-type" class="section level2">
<h2>Residence type</h2>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>Residence_type)</span></code></pre></div>
<pre><code>##  chr [1:5109] &quot;Urban&quot; &quot;Rural&quot; &quot;Rural&quot; &quot;Urban&quot; &quot;Rural&quot; &quot;Urban&quot; &quot;Rural&quot; ...</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>Residence_type)</span></code></pre></div>
<pre><code>## 
## Rural Urban 
##  2513  2596</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>Residence_type)<span class="sc">/</span><span class="fu">nrow</span>(data), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
## Rural Urban 
##  0.49  0.51</code></pre>
<p>The column <strong>Residence_type</strong> informs us if the patient
lives in a rural (49%) or an urban environment (51%).</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>residence_stroke <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Residence_type, stroke) <span class="sc">%&gt;%</span> </span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>residence_stroke</span></code></pre></div>
<pre><code>##               stroke
## Residence_type    0    1
##          Rural 2399  114
##          Urban 2461  135</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(residence_stroke)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  residence_stroke
## X-squared = 1.075, df = 1, p-value = 0.2998</code></pre>
<p>It is not associated with <strong>stroke</strong> and will not be
included in the model.</p>
</div>
<div id="glucose-level" class="section level2">
<h2>Glucose level</h2>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>avg_glucose_level)</span></code></pre></div>
<pre><code>##  num [1:5109] 229 202 106 171 174 ...</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(avg_glucose_level))<span class="sc">+</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>)<span class="sc">+</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-26-1.png" width="768" /></p>
<p>Next is the average glucose level in the blood which is given in the
column <strong>avg_glucose_level</strong>. The distribution is
approaching a bimodal distribution with a high peak at around 75 and a
second small peak at 220.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> stroke, <span class="at">y =</span> avg_glucose_level))<span class="sc">+</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-27-1.png" width="768" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lmp</span>(avg_glucose_level <span class="sc">~</span> stroke, <span class="at">data =</span> data))</span></code></pre></div>
<pre><code>## [1] &quot;Settings:  unique SS &quot;
## Analysis of Variance Table
## 
## Response: avg_glucose_level
##             Df R Sum Sq R Mean Sq Iter  Pr(Prob)    
## stroke       1   182494    182494 5000 &lt; 2.2e-16 ***
## Residuals 5107 10292642      2015                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb100"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&#39;Correlation between age and avg_glucose_level &#39;</span>, <span class="fu">round</span>(<span class="fu">cor</span>(data<span class="sc">$</span>age, data<span class="sc">$</span>avg_glucose_level), <span class="dv">2</span>), <span class="st">&#39;</span><span class="sc">\n</span><span class="st">&#39;</span>)</span></code></pre></div>
<pre><code>## Correlation between age and avg_glucose_level  0.24</code></pre>
<p>Patients who suffered from a stroke have on average a higher average
glucose level as shown in the boxplots and the ANOVA with a permutation
test. It shows only a small positive correlation (r = 0.24) with
age.</p>
<div class="sourceCode" id="cb102"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(age, avg_glucose_level))<span class="sc">+</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density2d_filled</span>()<span class="sc">+</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>stroke)<span class="sc">+</span></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)<span class="sc">+</span></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&#39;none&#39;</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-28-1.png" width="768" /></p>
<p>When looking at the 2D kernel density estimate of
<strong>age</strong> and <strong>avg_glucose_level</strong> separated
for patient who suffered from a stroke and those that did not, we can
see that patients who had a stroke were on average older and/or had a
higher average glucose level. Therefore, the average glucose level in
the blood could help in our prediction.</p>
</div>
<div id="bmi" class="section level2">
<h2>BMI</h2>
<div class="sourceCode" id="cb103"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>bmi)</span></code></pre></div>
<pre><code>##  chr [1:5109] &quot;36.6&quot; &quot;N/A&quot; &quot;32.5&quot; &quot;34.4&quot; &quot;24&quot; &quot;29&quot; &quot;27.4&quot; &quot;22.8&quot; &quot;N/A&quot; ...</code></pre>
<div class="sourceCode" id="cb105"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>NA_values <span class="ot">&lt;-</span> <span class="fu">unique</span>(data<span class="sc">$</span>bmi[<span class="fu">which</span>(<span class="fu">is.na</span>(<span class="fu">as.numeric</span>(data<span class="sc">$</span>bmi)))])</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>NA_values</span></code></pre></div>
<pre><code>## [1] &quot;N/A&quot;</code></pre>
<div class="sourceCode" id="cb107"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>bmi <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(NA_values, <span class="cn">NA</span>, data<span class="sc">$</span>bmi))</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data<span class="sc">$</span>bmi))</span></code></pre></div>
<pre><code>## [1] 201</code></pre>
<p>The column containing the body mass index (BMI) of the patients
contains 201 missing values that needed recoding.</p>
<div class="sourceCode" id="cb109"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### Association between stroke and having a missing value at BMI&#39;</span>)</span></code></pre></div>
<div id="association-between-stroke-and-having-a-missing-value-at-bmi"
class="section level3">
<h3>Association between stroke and having a missing value at BMI</h3>
<div class="sourceCode" id="cb110"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>stroke, <span class="fu">is.na</span>(data<span class="sc">$</span>bmi))</span></code></pre></div>
<pre><code>##    
##     FALSE TRUE
##   0  4699  161
##   1   209   40</code></pre>
<div class="sourceCode" id="cb112"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(data<span class="sc">$</span>stroke, <span class="fu">is.na</span>(data<span class="sc">$</span>bmi)))</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  table(data$stroke, is.na(data$bmi))
## X-squared = 98.559, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>We can also see that the data is not missing at random, since
patients with missing BMI values also suffered more often from a stroke
(20.0%) compared to those without missing values (4.3%). Excluding the
patients with missing values would make the data set even more
unbalanced and a naive imputation method such as a median imputation
would most likely lead to a bias in the prediction of
<strong>stroke</strong> later.</p>
<div class="sourceCode" id="cb114"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>trc <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&#39;cv&#39;</span>,</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">number =</span> <span class="dv">5</span>)</span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>bmi_imputation_model <span class="ot">&lt;-</span> <span class="fu">train</span>(bmi <span class="sc">~</span> .,</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&#39;ranger&#39;</span>,</span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data[<span class="sc">!</span><span class="fu">is.na</span>(data<span class="sc">$</span>bmi), ],</span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">trControl =</span> trc)</span>
<span id="cb114-8"><a href="#cb114-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-9"><a href="#cb114-9" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>bmi[<span class="fu">is.na</span>(data<span class="sc">$</span>bmi)] <span class="ot">&lt;-</span> <span class="fu">predict</span>(bmi_imputation_model, </span>
<span id="cb114-10"><a href="#cb114-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">newdata =</span> data[<span class="fu">is.na</span>(data<span class="sc">$</span>bmi), ])</span></code></pre></div>
<p>We therefore use all the other columns to perform an imputation with
a random forest using the data without missing values as a training set
with 5 times cross-validation and predict the missing BMI values. A
random forest imputation has the advantage here that it can deal with
the different data types and should out of the box give a more accurate
imputation than just the median, since our sample size is sufficiently
large.</p>
<div class="sourceCode" id="cb115"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(stroke, bmi))<span class="sc">+</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">15</span>)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-32-1.png" width="768" /></p>
<div class="sourceCode" id="cb116"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lmp</span>(bmi <span class="sc">~</span> stroke, <span class="at">data =</span> data))</span></code></pre></div>
<pre><code>## [1] &quot;Settings:  unique SS &quot;
## Analysis of Variance Table
## 
## Response: bmi
##             Df R Sum Sq R Mean Sq Iter  Pr(Prob)    
## stroke       1      548    547.73 5000 &lt; 2.2e-16 ***
## Residuals 5107   304329     59.59                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>After imputation an ANOVA with a permutation test shows that patients
with a stroke had on average a higher BMI. We will therefore include the
BMI in our model.</p>
</div>
</div>
<div id="smoking-status" class="section level2">
<h2>Smoking status</h2>
<div class="sourceCode" id="cb118"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>smoking_status)</span></code></pre></div>
<pre><code>##  chr [1:5109] &quot;formerly smoked&quot; &quot;never smoked&quot; &quot;never smoked&quot; &quot;smokes&quot; ...</code></pre>
<div class="sourceCode" id="cb120"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>smoking_status)</span></code></pre></div>
<pre><code>## 
## formerly smoked    never smoked          smokes         Unknown 
##             884            1892             789            1544</code></pre>
<div class="sourceCode" id="cb122"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>smoking_status[data<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">&#39;Unknown&#39;</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(<span class="fu">is.na</span>(data<span class="sc">$</span>smoking_status)), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.302</code></pre>
<p>The last column <strong>smoking_status</strong> informs us if the
patient formerly smoked, never smoked or still smokes. The class
‘Unknown’ is recoded as NA, leading to a large amount of missing data
(30.2%).</p>
<div class="sourceCode" id="cb124"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">table</span>(data<span class="sc">$</span>work_type,</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>      data<span class="sc">$</span>smoking_status)<span class="sc">/</span><span class="fu">rowSums</span>(<span class="fu">table</span>(data<span class="sc">$</span>work_type,</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>      data<span class="sc">$</span>smoking_status)), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                
##                 formerly smoked never smoked smokes
##   children                 0.19         0.78   0.03
##   Govt_job                 0.25         0.53   0.22
##   Never_worked             0.00         1.00   0.00
##   Private                  0.23         0.53   0.24
##   Self-employed            0.31         0.50   0.19</code></pre>
<div class="sourceCode" id="cb126"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>age[data<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">&#39;children&#39;</span> <span class="sc">&amp;</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>                   <span class="sc">!</span><span class="fu">is.na</span>(data<span class="sc">$</span>smoking_status)])</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   10.00   11.00   12.00   12.35   13.00   16.00</code></pre>
<p>While checking for a connection between
<strong>smoking_status</strong> and <strong>work_type</strong> for a
possible association, I discovered that 19% of the patients marked as
children are classified as ‘formerly smoked’ and 3% as ‘smokes’. Since
75% of patients marked as children are 13 years or younger and the
maximum age is 16 years, I suspect some misclassification in the smoking
status. This and the high amount of missing data suggest to exclude it
from further analysis.</p>
</div>
</div>
<div id="prediction" class="section level1">
<h1>Prediction</h1>
<p>Now we want to use the variables <strong>age</strong>,
<strong>hypertension</strong>, <strong>avg_glucose_level</strong>, and
<strong>bmi</strong> to predict if a patient had a stroke or not. Since
the data set is highly imbalanced, classifying all patients as having no
stroke would lead to an accuracy of 0.95. Therefore it is important that
we rather use the specifity (does the model classify all patients who
had a stroke correctly) and the sensitivity (does the model classify all
patients who did not have a stroke correctly?) to rank our models.</p>
<p>We will use a 5-times cross-validation with 5 repetitions for all
models and use the specifity as an evaluation metric, since it is more
important to catch all cases with a stroke. The first model is a
standard logistic regression.</p>
<div id="standard-model" class="section level2">
<h2>Standard model</h2>
<div class="sourceCode" id="cb128"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nr =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data),</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">weights =</span> <span class="fu">ifelse</span>(stroke <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.95</span>, <span class="fl">0.05</span>))</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>trc <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&#39;repeatedcv&#39;</span>,</span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">number =</span> <span class="dv">5</span>,</span>
<span id="cb128-7"><a href="#cb128-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">repeats =</span> <span class="dv">10</span>,</span>
<span id="cb128-8"><a href="#cb128-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">summaryFunction =</span> twoClassSummary)</span>
<span id="cb128-9"><a href="#cb128-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-10"><a href="#cb128-10" aria-hidden="true" tabindex="-1"></a>model_standard <span class="ot">&lt;-</span> <span class="fu">train</span>(stroke <span class="sc">~</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi,</span>
<span id="cb128-11"><a href="#cb128-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&#39;glm&#39;</span>,</span>
<span id="cb128-12"><a href="#cb128-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">trControl =</span> trc,</span>
<span id="cb128-13"><a href="#cb128-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>,</span>
<span id="cb128-14"><a href="#cb128-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data,</span>
<span id="cb128-15"><a href="#cb128-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>)</span>
<span id="cb128-16"><a href="#cb128-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-17"><a href="#cb128-17" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(model_standard)</span></code></pre></div>
<pre><code>## Cross-Validated (5 fold, repeated 10 times) Confusion Matrix 
## 
## (entries are percentual average cell counts across resamples)
##  
##           Reference
## Prediction    0    1
##          0 95.1  4.9
##          1  0.0  0.0
##                             
##  Accuracy (average) : 0.9513</code></pre>
<p>As already expected the standard model classified all patients as not
having a stroke leading to an accuracy of 0.95. This means, on the other
Hand, that all patients who had a stroke were misclassified (specifity =
0).</p>
</div>
<div id="weights-and-smote" class="section level2">
<h2>Weights and SMOTE</h2>
<p>To solve the problem with the imbalanced data we will give the
patients who suffered from a stroke a higher weight (0.95) compared to
the ones who did not (0.05). As a second approach we will use SMOTE
(Synthetic minority oversampling technique).</p>
<div class="sourceCode" id="cb130"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>model_weights <span class="ot">&lt;-</span> <span class="fu">train</span>(stroke <span class="sc">~</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi,</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&#39;glm&#39;</span>,</span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">trControl =</span> trc,</span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>,</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">weights =</span> weights,</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data,</span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>)</span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a>trc_smote <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&#39;repeatedcv&#39;</span>,</span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">number =</span> <span class="dv">5</span>,</span>
<span id="cb130-11"><a href="#cb130-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">repeats =</span> <span class="dv">10</span>,</span>
<span id="cb130-12"><a href="#cb130-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">sampling =</span> <span class="st">&#39;smote&#39;</span>,</span>
<span id="cb130-13"><a href="#cb130-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">summaryFunction =</span> twoClassSummary)</span>
<span id="cb130-14"><a href="#cb130-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-15"><a href="#cb130-15" aria-hidden="true" tabindex="-1"></a>model_smote <span class="ot">&lt;-</span> <span class="fu">train</span>(stroke <span class="sc">~</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi,</span>
<span id="cb130-16"><a href="#cb130-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&#39;glm&#39;</span>,</span>
<span id="cb130-17"><a href="#cb130-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">trControl =</span> trc_smote,</span>
<span id="cb130-18"><a href="#cb130-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>,</span>
<span id="cb130-19"><a href="#cb130-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data,</span>
<span id="cb130-20"><a href="#cb130-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>)</span>
<span id="cb130-21"><a href="#cb130-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-22"><a href="#cb130-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-23"><a href="#cb130-23" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">resamples</span>(<span class="fu">list</span>(<span class="at">standard =</span> model_standard,</span>
<span id="cb130-24"><a href="#cb130-24" aria-hidden="true" tabindex="-1"></a>               <span class="at">weights =</span> model_weights,</span>
<span id="cb130-25"><a href="#cb130-25" aria-hidden="true" tabindex="-1"></a>               <span class="at">smote =</span> model_smote))</span>
<span id="cb130-26"><a href="#cb130-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-27"><a href="#cb130-27" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tmp)[[<span class="st">&#39;statistics&#39;</span>]][<span class="fu">c</span>(<span class="st">&#39;Spec&#39;</span>, <span class="st">&#39;Sens&#39;</span>)]</span></code></pre></div>
<pre><code>## $Spec
##               Min.   1st Qu. Median      Mean 3rd Qu. Max. NA&#39;s
## standard 0.0000000 0.0000000    0.0 0.0000000    0.00 0.00    0
## weights  0.6122449 0.7638776    0.8 0.8019837    0.84 0.92    0
## smote    0.6326531 0.7600000    0.8 0.7902531    0.82 0.90    0
## 
## $Sens
##               Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA&#39;s
## standard 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000    0
## weights  0.6851852 0.7276235 0.7345679 0.7341975 0.7415123 0.7633745    0
## smote    0.7047325 0.7278807 0.7355967 0.7348148 0.7404835 0.7654321    0</code></pre>
<div class="sourceCode" id="cb132"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">bwplot</span>(tmp, <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>)</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">bwplot</span>(tmp, <span class="at">metric =</span> <span class="st">&#39;Sens&#39;</span>)</span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(A, B)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-36-1.png" width="768" /></p>
<p>Both approaches improve the specifity of the model to 0.79 while
decreasing its sensitivity to 0.73. This means that more patients who
did not have a stroke are misclassified, but most patients who had a
stroke were correctly classified.</p>
</div>
<div id="regularization" class="section level2">
<h2>Regularization</h2>
<p>We can try to improve the logistic regression by also using two
regularization approaches, namely ridge and lasso regression.</p>
<div class="sourceCode" id="cb133"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>model_weights_reg <span class="ot">&lt;-</span> <span class="fu">train</span>(stroke <span class="sc">~</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi,</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&#39;glmnet&#39;</span>,</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">trControl =</span> trc,</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>,</span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">weights =</span> weights,</span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data,</span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>,</span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(</span>
<span id="cb133-9"><a href="#cb133-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">alpha =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb133-10"><a href="#cb133-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">lambda =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">10</span><span class="sc">/</span><span class="dv">10</span></span>
<span id="cb133-11"><a href="#cb133-11" aria-hidden="true" tabindex="-1"></a>      ))</span>
<span id="cb133-12"><a href="#cb133-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-13"><a href="#cb133-13" aria-hidden="true" tabindex="-1"></a>model_smote_reg <span class="ot">&lt;-</span> <span class="fu">train</span>(stroke <span class="sc">~</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi,</span>
<span id="cb133-14"><a href="#cb133-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">method =</span> <span class="st">&#39;glmnet&#39;</span>,</span>
<span id="cb133-15"><a href="#cb133-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">trControl =</span> trc_smote,</span>
<span id="cb133-16"><a href="#cb133-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span>,</span>
<span id="cb133-17"><a href="#cb133-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> data,</span>
<span id="cb133-18"><a href="#cb133-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>,</span>
<span id="cb133-19"><a href="#cb133-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(</span>
<span id="cb133-20"><a href="#cb133-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">alpha =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb133-21"><a href="#cb133-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">lambda =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">10</span><span class="sc">/</span><span class="dv">10</span></span>
<span id="cb133-22"><a href="#cb133-22" aria-hidden="true" tabindex="-1"></a>      ))</span>
<span id="cb133-23"><a href="#cb133-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-24"><a href="#cb133-24" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_weights_reg)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-37-1.png" width="768" /></p>
<div class="sourceCode" id="cb134"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_smote_reg)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-37-2.png" width="768" /></p>
<p>Both the approach with weights and with SMOTE optimized the specifity
using lasso regression. Let’s see how they perform compared to the
previous models.</p>
<div class="sourceCode" id="cb135"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">resamples</span>(<span class="fu">list</span>(<span class="at">standard =</span> model_standard,</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">weights =</span> model_weights,</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">smote =</span> model_smote,</span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">weights_reg =</span> model_weights_reg,</span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">smote_reg =</span> model_smote_reg))</span>
<span id="cb135-6"><a href="#cb135-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-7"><a href="#cb135-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-8"><a href="#cb135-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-9"><a href="#cb135-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tmp)[[<span class="st">&#39;statistics&#39;</span>]][<span class="fu">c</span>(<span class="st">&#39;Spec&#39;</span>, <span class="st">&#39;Sens&#39;</span>)]</span></code></pre></div>
<pre><code>## $Spec
##                  Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA&#39;s
## standard    0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000    0
## weights     0.6122449 0.7638776 0.8000000 0.8019837 0.8400000 0.9200000    0
## smote       0.6326531 0.7600000 0.8000000 0.7902531 0.8200000 0.9000000    0
## weights_reg 0.7200000 0.8163265 0.8283673 0.8317143 0.8550000 0.9183673    0
## smote_reg   0.7346939 0.8200000 0.8485714 0.8437551 0.8793878 0.9400000    0
## 
## $Sens
##                  Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA&#39;s
## standard    1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000    0
## weights     0.6851852 0.7276235 0.7345679 0.7341975 0.7415123 0.7633745    0
## smote       0.7047325 0.7278807 0.7355967 0.7348148 0.7404835 0.7654321    0
## weights_reg 0.6738683 0.6995885 0.7067901 0.7084774 0.7191358 0.7427984    0
## smote_reg   0.6502058 0.6838992 0.6954733 0.6922840 0.7024177 0.7222222    0</code></pre>
<div class="sourceCode" id="cb137"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">bwplot</span>(tmp, <span class="at">metric =</span> <span class="st">&#39;Spec&#39;</span>)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">bwplot</span>(tmp, <span class="at">metric =</span> <span class="st">&#39;Sens&#39;</span>)</span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(A, B)</span></code></pre></div>
<p><img src="stroke_prediction_files/figure-html/unnamed-chunk-38-1.png" width="768" /></p>
<div class="sourceCode" id="cb138"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">asis_output</span>(<span class="st">&#39;### Balanced accuracy&#39;</span>)</span></code></pre></div>
<div id="balanced-accuracy" class="section level3">
<h3>Balanced accuracy</h3>
<div class="sourceCode" id="cb139"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((<span class="fu">summary</span>(tmp)[[<span class="st">&#39;statistics&#39;</span>]][[<span class="st">&#39;Sens&#39;</span>]][, <span class="st">&#39;Mean&#39;</span>] <span class="sc">+</span> <span class="fu">summary</span>(tmp)[[<span class="st">&#39;statistics&#39;</span>]][[<span class="st">&#39;Spec&#39;</span>]][, <span class="st">&#39;Mean&#39;</span>])<span class="sc">/</span><span class="dv">2</span>, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##    standard     weights       smote weights_reg   smote_reg 
##        0.50        0.77        0.76        0.77        0.77</code></pre>
<p>The lasso regression with weights achieved on average a specifity of
0.83 and with smote of 0.85, will decreasing the sensitivity to 0.71 and
0.69, respectively. When looking at the balanced accuracy (the sum of
the specifity and the sensitivity divided by two) both approaches with
regularization perform slightly better compared to the approaches
without. Since the lasso regression using SMOTE achieves the highest
specifity it may be the best model, since it should be more beneficial
to classify patients with a stroke correctly, while risking the
misclassification of patients without a stroke.</p>
</div>
</div>
</div>
</div>

   
   
            
      

  <script>
    $(document).ready(function () {

			
 		
	    });
  </script>



    <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
	document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>
  
</body>
</html>
